name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Node
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: |
          $env:VITE_API_URL = [Environment]::GetEnvironmentVariable("VITE_API_URL", "Machine")
          Write-Host "VITE_API_URL = $env:VITE_API_URL"
          npm run build
    
      - name: Deploy to IIS
        run: |
          Remove-Item "C:\inetpub\AquaticFishFrontend\*" -Recurse -Force
          Copy-Item ".\dist\*" "C:\inetpub\AquaticFishFrontend" -Recurse -Force

      - name: Restart Frontend App Pool
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "AquaticFishFrontend"
